import Logo from '@/app/_components/Logo';
import Navigation from '@/app/_components/navigation';
import '@/app/_styles/globals.css';

export const metadata = {
  title: {
    template: '%s - The Wild Oasis Demi',
    default: 'Welcome to the wild oasis',
  },
  description:
    'Luxurious cabin hotel, located in the heart of Lagos Nigeria, surrounded by beautiful moutains and dark forests',
  // description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-primary-950 text-primary-100">
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>Copyright by Wild-Oasis-Demi</footer>
      </body>
    </html>
  );
}
