import '@/app/_styles/globals.css';
import { Josefin_Sans } from 'next/font/google';
import Header from './_components/Header';

const josefin = Josefin_Sans({ subsets: ['latin'], display: 'swap' });

export const metadata = {
  title: {
    template: '%s - The Wild Oasis Demi',
    default: 'Welcome to the wild oasis',
  },
  description:
    'Luxurious cabin hotel, located in the heart of Lagos Nigeria, surrounded by beautiful moutains and dark forests',
  // description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} antialiased min-h-screen bg-primary-950 text-primary-100 flex flex-col`}
      >
        <Header />
        <div className="flex-1 px-8 py-12">
          <main className="mx-auto max-w-7xl ">{children}</main>
        </div>
      </body>
    </html>
  );
}
